import Foundation

// MARK: - Errors

/// Errors raised while rendering service configuration.
public enum GeneratorError: Error, Equatable, CustomStringConvertible {
    /// A PHP branch was requested (default site, FPM pool, php.ini) but is not installed.
    case phpBranchNotInstalled(String)
    /// A component/branch needed for rendering is not installed, e.g. `"mysql 8.4"`.
    case componentNotInstalled(String)
    /// A config-supplied value is unsafe or malformed (newline → directive injection, bad size, …).
    case invalidValue(key: String, value: String)
    /// A unix socket path exceeds the macOS `sun_path` limit.
    case socketPathTooLong(String)
    /// The installed PHP record lacks `extensionDirRel` (manifest `extension_dir_rel`).
    case missingExtensionDir(branch: String)
    /// A PHP extension was explicitly enabled (or Xdebug mode set) but the branch's package does not ship it.
    case extensionUnavailable(branch: String, name: String)

    public var description: String {
        switch self {
        case .phpBranchNotInstalled(let b): return "PHP \(b) is not installed"
        case .componentNotInstalled(let c): return "\(c) is not installed"
        case .invalidValue(let k, let v): return "Invalid value for \(k): \(v.debugDescription)"
        case .socketPathTooLong(let p):
            return "Unix socket path too long (\(p.utf8.count) bytes, max \(Paths.maxSocketPathBytes - 1)): \(p)"
        case .missingExtensionDir(let b): return "PHP \(b) install record has no extension_dir_rel"
        case .extensionUnavailable(let b, let n): return "PHP \(b) package has no \(n) extension"
        }
    }
}

// MARK: - Output

/// One rendered configuration file. `path` is absolute and must live under `Paths.root`.
public struct GeneratedFile: Sendable, Equatable {
    public var path: URL
    public var contents: String
    /// POSIX permission bits, e.g. `0o644`.
    public var mode: Int

    public init(path: URL, contents: String, mode: Int = 0o644) {
        self.path = path
        self.contents = contents
        self.mode = mode
    }
}

// MARK: - PHP branch ordering

/// `major.minor` PHP branch with numeric ordering ("8.10" > "8.9").
public struct PHPBranch: Comparable, Hashable, Sendable, CustomStringConvertible {
    public let major: Int
    public let minor: Int

    public init?(_ string: String) {
        let parts = string.split(separator: ".", omittingEmptySubsequences: false)
        guard parts.count == 2, let major = Int(parts[0]), let minor = Int(parts[1]),
              major >= 0, minor >= 0,
              parts.allSatisfy({ $0.allSatisfy(\.isASCII) && $0.allSatisfy(\.isNumber) }) else { return nil }
        self.major = major
        self.minor = minor
    }

    public var description: String { "\(major).\(minor)" }

    public static func < (lhs: PHPBranch, rhs: PHPBranch) -> Bool {
        (lhs.major, lhs.minor) < (rhs.major, rhs.minor)
    }
}

// MARK: - Line builder

/// Tiny line builder shared by all generators. Quoting/escaping and injection checks live here only.
struct ConfigText {
    enum Dialect {
        /// Apache: only `"` is escapable inside quotes (a `\` before anything else is kept literally).
        case apache
        /// php.ini / php-fpm.conf / my.cnf / redis.conf: `\` and `"` are escaped.
        case backslash
        /// YAML (elasticsearch.yml): double-quoted scalars, `\\` and `"` escaped.
        case yaml
    }

    static let header = "Generated by RAMP — do not edit"

    let dialect: Dialect
    /// Separator between key and value: `" "`, `" = "` or `"="`.
    let separator: String
    let commentPrefix: String
    private(set) var lines: [String] = []
    private var indent = 0

    init(dialect: Dialect, separator: String, commentPrefix: String) {
        self.dialect = dialect
        self.separator = separator
        self.commentPrefix = commentPrefix
        lines.append("\(commentPrefix) \(Self.header)")
    }

    /// Rejects characters that would end the current directive (newline, CR, NUL).
    static func validate(_ value: String, key: String) throws {
        if value.unicodeScalars.contains(where: { $0 == "\n" || $0 == "\r" || $0 == "\0" || $0 == "\u{2028}" }) {
            throw GeneratorError.invalidValue(key: key, value: value)
        }
    }

    func quote(_ value: String, key: String = "value") throws -> String {
        try Self.validate(value, key: key)
        var escaped = ""
        for ch in value {
            switch (dialect, ch) {
            case (.apache, "\""), (.backslash, "\""), (.backslash, "\\"), (.yaml, "\""), (.yaml, "\\"):
                escaped.append("\\")
            default: break
            }
            escaped.append(ch)
        }
        return "\"\(escaped)\""
    }

    mutating func blank() { lines.append("") }

    mutating func comment(_ text: String) { lines.append(pad + "\(commentPrefix) \(text)") }

    /// Raw line (constants only — never config-supplied data without `quote`).
    mutating func line(_ text: String) throws {
        try Self.validate(text, key: "line")
        lines.append(pad + text)
    }

    mutating func directive(_ key: String, _ value: String, quoted: Bool = false) throws {
        try Self.validate(key, key: "key")
        let v = quoted ? try quote(value, key: key) : value
        try Self.validate(v, key: key)
        lines.append(pad + key + separator + v)
    }

    mutating func directive(_ key: String, _ value: URL) throws {
        try directive(key, ConfigText.path(value), quoted: true)
    }

    mutating func block(_ open: String, _ close: String, _ body: (inout ConfigText) throws -> Void) throws {
        try line(open)
        indent += 1
        try body(&self)
        indent -= 1
        try line(close)
    }

    var rendered: String { lines.joined(separator: "\n") + "\n" }

    private var pad: String { String(repeating: "    ", count: indent) }

    /// Filesystem path without trailing slash (except `/`).
    static func path(_ url: URL) -> String {
        var p = url.path(percentEncoded: false)
        while p.count > 1 && p.hasSuffix("/") { p.removeLast() }
        return p
    }
}

// MARK: - Shared helpers

enum GeneratorSupport {
    /// Installed + enabled PHP branches, numerically sorted ascending.
    static func enabledPHPBranches(_ config: RampConfig) -> [String] {
        (config.installed["php"] ?? [:]).keys
            .filter { config.php.branches[$0]?.enabled ?? true }
            .compactMap { b in PHPBranch(b).map { (b, $0) } }
            .sorted { $0.1 < $1.1 }
            .map(\.0)
    }

    static func installedPHP(_ config: RampConfig, branch: String) throws -> InstalledPackage {
        guard PHPBranch(branch) != nil, let pkg = config.installed["php"]?[branch] else {
            throw GeneratorError.phpBranchNotInstalled(branch)
        }
        return pkg
    }

    /// Highest installed branch of a non-PHP component (numeric compare), or nil.
    static func highestBranch(_ config: RampConfig, component: String) -> String? {
        (config.installed[component] ?? [:]).keys
            .compactMap { b in PHPBranch(b).map { (b, $0) } }
            .max { $0.1 < $1.1 }?.0
    }

    static func validateSocket(_ url: URL, paths: Paths) throws {
        do { try paths.validateSocketPath(url) } catch {
            throw GeneratorError.socketPathTooLong(url.path(percentEncoded: false))
        }
    }

    static func validatePort(_ port: Int, key: String) throws {
        guard (1...65535).contains(port) else {
            throw GeneratorError.invalidValue(key: key, value: String(port))
        }
    }

    /// `1G`, `512M`, `4096`, `512mb` style sizes.
    static func validateSize(_ value: String, key: String) throws {
        guard value.range(of: #"^[0-9]+([KkMmGg][Bb]?)?$"#, options: .regularExpression) != nil else {
            throw GeneratorError.invalidValue(key: key, value: value)
        }
    }

    /// Bare token (no spaces/quotes), e.g. IP addresses.
    static func validateToken(_ value: String, key: String) throws {
        guard !value.isEmpty, value.range(of: #"^[A-Za-z0-9.:_\-]+$"#, options: .regularExpression) != nil else {
            throw GeneratorError.invalidValue(key: key, value: value)
        }
    }
}

// MARK: - Renderer

/// Renders every service configuration from `ramp.json`. Pure: no disk, no clock, no environment.
public enum ConfigRenderer {
    /// Deterministic order: httpd.conf + vhosts/<domain>.conf (sorted), then per PHP branch (ascending) php-fpm.conf + php.ini + conf.d/*.ini,
    /// then my.cnf, then redis.conf, then phpMyAdmin config.inc.php + .user.ini, then elasticsearch.yml + jvm.options.d/ramp.options, then Elasticvue api/default_clusters.json. Components that are not installed are skipped.
    public static func renderAll(config: RampConfig, paths: Paths) throws -> [GeneratedFile] {
        var files: [GeneratedFile] = []
        if !(config.installed["apache"] ?? [:]).isEmpty {
            files.append(GeneratedFile(path: paths.apacheConf,
                                       contents: try ApacheConfigGenerator(config: config, paths: paths).render()))
            files += try VhostConfigGenerator(config: config, paths: paths).files()
        }
        let fpm = PHPFPMConfigGenerator(config: config, paths: paths)
        let ini = PHPIniGenerator(config: config, paths: paths)
        for branch in GeneratorSupport.enabledPHPBranches(config) {
            files.append(GeneratedFile(path: paths.fpmConf(branch: branch), contents: try fpm.render(branch: branch)))
            files += try ini.files(branch: branch)
            files.append(try ini.cliIni(branch: branch))   // terminal shims; never reloads FPM (affectedServices)
        }
        if config.installed["mysql"]?[config.mysql.branch] != nil {
            files.append(GeneratedFile(path: paths.mysqlConf(major: config.mysql.branch),
                                       contents: try MySQLConfigGenerator(config: config, paths: paths).render()))
        }
        if !(config.installed["redis"] ?? [:]).isEmpty {
            files.append(GeneratedFile(path: paths.redisConf,
                                       contents: try RedisConfigGenerator(config: config, paths: paths).render()))
        }
        // phpMyAdmin config.inc.php + .user.ini (04-04), only once a blowfish secret is stored.
        let pma = PhpMyAdminConfigGenerator(config: config, paths: paths)
        if try pma.site() != nil { files += try pma.files() }
        // Optional service, appended last (empty when not installed).
        files += try ElasticsearchConfigGenerator(config: config, paths: paths).files()
        // Elasticvue default cluster → the ES port (only with Elasticsearch installed).
        files += try ElasticvueConfigGenerator(config: config, paths: paths).files()
        return files
    }

    /// Directories whose files of `ext` are fully owned by the renderer: anything there that
    /// `renderAll` no longer produces is stale and may be pruned (`ConfigWriter.prune`, 03-03).
    /// Apache: `conf/apache/vhosts` (`conf`); PHP: `conf/php/<b>/conf.d` (`ini`) of every enabled branch;
    /// Elasticsearch (installed): `conf/elasticsearch/jvm.options.d` (`options`).
    public static func managedDirectories(config: RampConfig, paths: Paths) -> [(dir: URL, ext: String)] {
        var dirs: [(dir: URL, ext: String)] = [(paths.apacheVhostsDir, "conf")]
        for branch in GeneratorSupport.enabledPHPBranches(config) {
            dirs.append((paths.phpConfD(branch: branch), "ini"))
        }
        if ElasticsearchConfigGenerator.isInstalled(config) {
            dirs.append((paths.elasticsearchJvmOptionsDir, "options"))
        }
        return dirs
    }
}
