import Foundation
import Security

/// phpMyAdmin (plan 04-04): renders `<pma current>/config.inc.php` (0600 — contains the MySQL root password)
/// and `<pma current>/.user.ini`, and resolves the site (package dir + PHP branch) that
/// `ApacheConfigGenerator` aliases at `/phpmyadmin` in the localhost site only.
///
/// phpMyAdmin 5.2 reads `ROOT_PATH . 'config.inc.php'` (`libraries/vendor_config.php` → `configFile`), and
/// PHP-FPM reads `.user.ini` from the script's directory (the alias target is outside DOCUMENT_ROOT).
/// Pure: the blowfish secret is generated by `StackController` (`generateSecret()`) and stored in ramp.json.
public struct PhpMyAdminConfigGenerator: Sendable {
    public static let component = "phpmyadmin"
    /// phpMyAdmin 5.2 wants a 32-byte secret.
    public static let secretLength = 32
    static let secretAlphabet = Array("ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789".utf8)
    /// Package subdirectories that must never be served.
    public static let deniedDirectories = ["libraries", "templates", "setup", "sql", "vendor", "tmp"]

    /// What Apache needs: the aliased package directory and the PHP branch whose FPM runs it.
    public struct Site: Sendable, Equatable {
        public var directory: URL
        public var phpBranch: String
    }

    public let config: RampConfig
    public let paths: Paths

    public init(config: RampConfig, paths: Paths) {
        self.config = config
        self.paths = paths
    }

    public static func isInstalled(_ config: RampConfig) -> Bool {
        GeneratorSupport.highestBranch(config, component: component) != nil
    }

    /// `<root>/tmp/phpmyadmin` (`$cfg['TempDir']`, created 0700 by `StackController`).
    public static func tempDir(_ paths: Paths) -> URL {
        paths.tmp.appending(path: "phpmyadmin", directoryHint: .isDirectory)
    }

    /// `<root>/phpmyadmin/<branch>/current` of the highest installed branch, or nil.
    public var packageDirectory: URL? {
        GeneratorSupport.highestBranch(config, component: Self.component)
            .map { paths.current(component: Self.component, branch: $0) }
    }

    /// PHP branch: `phpmyadmin.phpBranch` (must be installed + enabled) or the highest enabled branch.
    public func phpBranch() throws -> String? {
        if let explicit = config.phpmyadmin.phpBranch {
            guard GeneratorSupport.enabledPHPBranches(config).contains(explicit) else {
                throw GeneratorError.phpBranchNotInstalled(explicit)
            }
            return explicit
        }
        return GeneratorSupport.enabledPHPBranches(config).last
    }

    /// Non-nil when phpMyAdmin is installed + enabled, a secret is stored and some PHP branch can run it.
    /// Without a secret nothing is rendered (StackController persists one before the first render).
    public func site() throws -> Site? {
        guard config.phpmyadmin.enabled, config.phpmyadmin.blowfishSecret != nil,
              let dir = packageDirectory, let branch = try phpBranch() else { return nil }
        return Site(directory: dir, phpBranch: branch)
    }

    /// `config.inc.php` (0600) + `.user.ini` (0644); `[]` when not installed / disabled / no PHP.
    /// Throws `invalidValue(phpmyadmin.blowfishSecret)` when the secret is missing or malformed.
    public func files() throws -> [GeneratedFile] {
        guard config.phpmyadmin.enabled, let dir = packageDirectory else { return [] }
        guard let secret = config.phpmyadmin.blowfishSecret, Self.isValidSecret(secret) else {
            throw GeneratorError.invalidValue(key: "phpmyadmin.blowfishSecret", value: config.phpmyadmin.blowfishSecret ?? "")
        }
        guard try phpBranch() != nil else { return [] }
        let socket = paths.mysqlSocket(major: config.mysql.branch)
        try GeneratorSupport.validateSocket(socket, paths: paths)

        func q(_ value: String, _ key: String) throws -> String { try Self.phpString(value, key: key) }
        let server = "$cfg['Servers'][$i]"
        let lines: [String] = [
            "<?php", "",
            "declare(strict_types=1);", "",
            "// \(ConfigText.header) (source of truth: ramp.json).", "",
            "$cfg['blowfish_secret'] = \(try q(secret, "phpmyadmin.blowfishSecret"));", "",
            "$i = 1;",
            "\(server)['auth_type'] = 'config';",
            "\(server)['host'] = 'localhost';",
            "\(server)['connect_type'] = 'socket';",
            "\(server)['socket'] = \(try q(ConfigText.path(socket), "mysql.socket"));",
            "\(server)['user'] = 'root';",
            "\(server)['password'] = \(try q(config.mysql.rootPassword, "mysql.rootPassword"));",
            "\(server)['AllowNoPassword'] = false;", "",
            "$cfg['TempDir'] = \(try q(ConfigText.path(Self.tempDir(paths)), "phpmyadmin.tempDir"));",
            "$cfg['UploadDir'] = '';",
            "$cfg['SaveDir'] = '';",
            "$cfg['VersionCheck'] = false;",
            "$cfg['SendErrorReports'] = 'never';",
            "$cfg['ExecTimeLimit'] = 300;",
            "$cfg['MaxNavigationItems'] = 250;",
            "$cfg['NavigationTreeEnableGrouping'] = false;",
        ]
        let userIni = [
            "; \(ConfigText.header)",
            "; Global dev default display_errors=On would flood phpMyAdmin with deprecations on new PHP.",
            "display_errors=Off",
            "error_reporting=E_ALL & ~E_DEPRECATED & ~E_USER_DEPRECATED",
        ]
        return [
            GeneratedFile(path: dir.appending(path: "config.inc.php", directoryHint: .notDirectory),
                          contents: lines.joined(separator: "\n") + "\n", mode: 0o600),
            GeneratedFile(path: dir.appending(path: ".user.ini", directoryHint: .notDirectory),
                          contents: userIni.joined(separator: "\n") + "\n", mode: 0o644),
        ]
    }

    // MARK: Helpers

    /// PHP single-quoted literal: `\` and `'` escaped; NUL / CR / LF / U+2028 rejected.
    static func phpString(_ value: String, key: String) throws -> String {
        try ConfigText.validate(value, key: key)
        var out = "'"
        for ch in value {
            if ch == "\\" || ch == "'" { out.append("\\") }
            out.append(ch)
        }
        return out + "'"
    }

    public static func isValidSecret(_ s: String) -> Bool {
        s.utf8.count == secretLength && s.utf8.allSatisfy { secretAlphabet.contains($0) }
    }

    /// 32 chars from `[A-Za-z0-9]` via `SecRandomCopyBytes`, rejection sampling (no modulo bias).
    public static func generateSecret() throws -> String {
        let n = secretAlphabet.count                      // 62
        let limit = UInt8(256 - 256 % n)                  // 248: accept 0..<248 (4 × 62)
        var result: [UInt8] = []
        while result.count < secretLength {
            var buffer = [UInt8](repeating: 0, count: 64)
            let status = SecRandomCopyBytes(kSecRandomDefault, buffer.count, &buffer)
            guard status == errSecSuccess else { throw POSIXError(.EIO) }
            for byte in buffer where byte < limit && result.count < secretLength {
                result.append(secretAlphabet[Int(byte) % n])
            }
        }
        return String(decoding: result, as: UTF8.self)
    }
}
