import Foundation
import Testing
@testable import RAMPCore

@Suite struct ApacheGeneratorTests {
    let root = GeneratorFixture.rootPath
    let logs = GeneratorFixture.logsPath

    func render(_ config: RampConfig = GeneratorFixture.config) throws -> String {
        try ApacheConfigGenerator(config: config, paths: GeneratorFixture.paths).render()
    }

    @Test func coreDirectives() throws {
        let text = try render()
        #expect(text.hasPrefix("# Generated by RAMP — do not edit\n"))
        #expect(text.contains("ServerRoot \"\(root)/apache/2.4/current\"\n"))
        #expect(text.contains("PidFile \"\(root)/run/httpd.pid\"\n"))
        #expect(text.contains("ServerName localhost\n"))
        #expect(text.contains("ErrorLog \"\(logs)/apache-error.log\"\n"))
        #expect(text.contains("CustomLog \"\(logs)/apache-access.log\" combined\n"))
        #expect(text.contains("DirectoryIndex index.php index.html\n"))
        #expect(text.contains("IncludeOptional \"\(root)/conf/apache/vhosts/*.conf\"\n"))
    }

    @Test func listenUsesConfiguredPortNever443() throws {
        let text = try render()
        #expect(text.contains("Listen 127.0.0.1:8080\n"))
        #expect(text.contains("Listen [::1]:8080\n"))
        #expect(text.contains("<VirtualHost *:8080>"))
        #expect(!text.contains("443"))
        #expect(!text.contains(":80\n"))
    }

    @Test func privilegedPortListensOnWildcardRestrictedToLocal() throws {
        var c = GeneratorFixture.config
        c.apache.port = 80
        let text = try render(c)
        // macOS refuses non-root binds of 127.0.0.1:80 (EACCES) but allows the wildcard address.
        #expect(text.contains("Listen 80\n"))
        #expect(!text.contains("Listen 127.0.0.1"))
        #expect(!text.contains("Listen [::1]"))
        #expect(text.contains("<Location \"/\">\n    Require local\n</Location>"))
    }

    @Test func unprivilegedPortKeepsLoopbackListenWithoutLocationGate() throws {
        let text = try render()
        #expect(!text.contains("<Location \"/\">"))
    }

    @Test func port443Rejected() {
        var c = GeneratorFixture.config
        c.apache.port = 443
        #expect(throws: GeneratorError.self) { try render(c) }
    }

    @Test func exactModuleSet() throws {
        let text = try render()
        let modules = text.split(separator: "\n").filter { $0.hasPrefix("LoadModule ") }.map(String.init)
        let expected = ["mpm_event", "authz_core", "authz_host", "unixd", "dir", "mime", "log_config", "alias",
                        "rewrite", "headers", "setenvif", "env", "expires", "deflate", "filter", "proxy", "proxy_fcgi"]
        #expect(modules == expected.map { "LoadModule \($0)_module modules/mod_\($0).so" })
        for forbidden in ["mpm_prefork", "fastcgi", "fcgid", "ssl", "listen 443"] {
            #expect(!text.lowercased().contains(forbidden), "must not contain \(forbidden)")
        }
        #expect(!text.contains("libphp"))
        #expect(!text.contains("php_module"))
        #expect(!text.contains("SSLEngine"))
    }

    @Test func noUserGroup() throws {
        let text = try render()
        for line in text.split(separator: "\n") {
            let t = line.trimmingCharacters(in: .whitespaces)
            #expect(!t.hasPrefix("User "))
            #expect(!t.hasPrefix("Group "))
        }
    }

    @Test func eventMPMSizing() throws {
        let text = try render()
        #expect(text.contains("StartServers 2\n"))
        #expect(text.contains("ThreadsPerChild 25\n"))
        #expect(text.contains("MaxRequestWorkers 150\n"))
    }

    @Test func accessControl() throws {
        let text = try render()
        #expect(text.contains("<Directory />\n    AllowOverride None\n    Require all denied\n</Directory>"))
        #expect(text.contains("<Directory \"\(root)/www\">"))
        #expect(text.contains("<Directory \"\(root)/www/default\">"))
        #expect(text.contains("AllowOverride All"))
        // "Require all granted" appears exactly for <root>/www and the docroot.
        #expect(text.components(separatedBy: "Require all granted").count - 1 == 2)
    }

    @Test func mimeTypesWithFallback() throws {
        let text = try render()
        #expect(text.contains("TypesConfig \"\(root)/apache/2.4/current/conf/mime.types\""))
        #expect(text.contains("AddType text/css .css"))
    }

    @Test func defaultVhostUsesHighestPHPBranch() throws {
        let text = try render()
        #expect(text.contains("DocumentRoot \"\(root)/www/default\""))
        #expect(text.contains("<FilesMatch \"\\.php$\">\n"))
        #expect(text.contains("SetHandler \"proxy:unix:\(root)/run/php8.5.sock|fcgi://localhost\"\n"))
    }

    @Test func branchesCompareNumerically() throws {
        var c = GeneratorFixture.config
        c.installed["php"]!["8.10"] = GeneratorFixture.pkg("8.10.0", ext: "x")
        c.installed["php"]!["8.9"] = GeneratorFixture.pkg("8.9.0", ext: "x")
        let text = try render(c)
        #expect(text.contains("run/php8.10.sock|"))
        #expect(PHPBranch("8.10")! > PHPBranch("8.9")!)
        #expect(PHPBranch("7.3")! < PHPBranch("8.2")!)
        #expect(PHPBranch("8") == nil)
        #expect(PHPBranch("8.x") == nil)
    }

    @Test func disabledBranchIsNotDefault() throws {
        var c = GeneratorFixture.config
        c.php.branches["8.5"] = PHPBranchSettings(enabled: false)
        #expect(try render(c).contains("run/php8.3.sock|"))
    }

    @Test func explicitDefaultPHPAndDocroot() throws {
        var c = GeneratorFixture.config
        c.apache.defaultPHP = "7.3"
        c.apache.documentRoot = "/Users/t/Sites/my site"
        let text = try render(c)
        #expect(text.contains("run/php7.3.sock|"))
        #expect(text.contains("DocumentRoot \"/Users/t/Sites/my site\""))
        #expect(text.contains("<Directory \"/Users/t/Sites/my site\">"))
        #expect(text.components(separatedBy: "Require all granted").count - 1 == 2)
    }

    @Test func defaultPHPNotInstalledThrows() {
        var c = GeneratorFixture.config
        c.apache.defaultPHP = "8.4"
        #expect(throws: GeneratorError.phpBranchNotInstalled("8.4")) { try render(c) }
    }

    @Test func proxyWorker() throws {
        let text = try render()
        #expect(text.contains("<Proxy \"fcgi://localhost\" enablereuse=off>\n</Proxy>"))
        #expect(text.contains("ProxyTimeout 300\n"))
    }

    @Test func injectionRejected() {
        var c = GeneratorFixture.config
        c.apache.documentRoot = "/tmp/x\"\nListen 443"
        #expect(throws: GeneratorError.self) { try render(c) }
        c.apache.documentRoot = "relative/path"
        #expect(throws: GeneratorError.self) { try render(c) }
    }

    @Test func quotesAreEscaped() throws {
        var c = GeneratorFixture.config
        c.apache.documentRoot = "/tmp/a\"b"
        #expect(try render(c).contains("DocumentRoot \"/tmp/a\\\"b\""))
    }

    @Test func golden() throws {
        #expect(try render() == ApacheGolden.text)
    }

    // MARK: phpMyAdmin (04-04)

    @Test func phpMyAdminAliasOnlyWithSecret() throws {
        #expect(!(try render()).contains("phpmyadmin"))
        var c = PhpMyAdminFixture.config
        c.phpmyadmin.blowfishSecret = nil
        #expect(!(try render(c)).contains("phpmyadmin"))
        c.phpmyadmin.blowfishSecret = PhpMyAdminFixture.secret
        c.phpmyadmin.enabled = false
        #expect(!(try render(c)).contains("phpmyadmin"))
    }

    @Test func phpMyAdminBlockInLocalhostSite() throws {
        #expect(try render(PhpMyAdminFixture.config) == ApacheGolden.text.replacingOccurrences(
            of: "        </FilesMatch>\n    </Directory>\n</VirtualHost>",
            with: "        </FilesMatch>\n    </Directory>\n" + ApacheGolden.phpMyAdminBlock + "</VirtualHost>"))
    }

    @Test func phpMyAdminUsesItsOwnBranch() throws {
        var c = PhpMyAdminFixture.config
        c.phpmyadmin.phpBranch = "8.2"
        let text = try render(c)
        let alias = try #require(text.range(of: "Alias /phpmyadmin"))
        #expect(text[..<alias.lowerBound].contains("run/php8.5.sock|"))     // default site unchanged
        #expect(text[alias.lowerBound...].contains("run/php8.2.sock|"))
        #expect(!text[alias.lowerBound...].contains("run/php8.5.sock|"))
        c.phpmyadmin.phpBranch = "8.4"
        #expect(throws: GeneratorError.phpBranchNotInstalled("8.4")) { try render(c) }
    }

    @Test func projectVhostsNeverExposePhpMyAdmin() throws {
        var c = VhostGeneratorFixture.config
        c.installed["phpmyadmin"] = PhpMyAdminFixture.config.installed["phpmyadmin"]
        c.phpmyadmin.blowfishSecret = PhpMyAdminFixture.secret
        let files = try ConfigRenderer.renderAll(config: c, paths: GeneratorFixture.paths)
        let vhosts = files.filter { $0.path.deletingLastPathComponent().lastPathComponent == "vhosts" }
        #expect(vhosts.count == 3)
        for f in vhosts { #expect(!f.contents.lowercased().contains("phpmyadmin")) }
        #expect(try ApacheConfigGenerator(config: c, paths: GeneratorFixture.paths).render().contains("Alias /phpmyadmin"))
    }

    // MARK: Elasticvue

    @Test func elasticvueAliasInLocalhostSite() throws {
        #expect(try render(ElasticvueFixture.config) == ApacheGolden.text.replacingOccurrences(
            of: "        </FilesMatch>\n    </Directory>\n</VirtualHost>",
            with: "        </FilesMatch>\n    </Directory>\n" + ApacheGolden.elasticvueBlock + "</VirtualHost>"))
    }

    @Test func elasticvueNeedsElasticsearch() throws {
        #expect(!(try render()).contains("elasticvue"))
        var c = ElasticvueFixture.config
        c.installed["elasticsearch"] = nil
        #expect(!(try render(c)).contains("elasticvue"))
    }

    @Test func elasticvueAfterPhpMyAdminAndNeverOnProjectVhosts() throws {
        var c = VhostGeneratorFixture.config
        c.installed["phpmyadmin"] = PhpMyAdminFixture.config.installed["phpmyadmin"]
        c.phpmyadmin.blowfishSecret = PhpMyAdminFixture.secret
        c.installed["elasticsearch"] = ElasticvueFixture.config.installed["elasticsearch"]
        c.installed["elasticvue"] = ElasticvueFixture.config.installed["elasticvue"]
        let files = try ConfigRenderer.renderAll(config: c, paths: GeneratorFixture.paths)
        for f in files where f.path.deletingLastPathComponent().lastPathComponent == "vhosts" {
            #expect(!f.contents.lowercased().contains("elasticvue"))
        }
        let text = try ApacheConfigGenerator(config: c, paths: GeneratorFixture.paths).render()
        let pma = try #require(text.range(of: "Alias /phpmyadmin"))
        let ev = try #require(text.range(of: "Alias /elasticvue"))
        let end = try #require(text.range(of: "</VirtualHost>"))
        #expect(pma.lowerBound < ev.lowerBound && ev.upperBound < end.lowerBound)
        // Static files only: no PHP handler inside the Elasticvue block.
        let block = text[ev.lowerBound..<end.lowerBound]
        #expect(!block.contains("SetHandler"))
    }

    @Test func regexEscaping() {
        #expect(ApacheConfigGenerator.regexEscaped("/a b/c.d/e+(f)") == #"/a b/c\.d/e\+\(f\)"#)
    }
}

/// Golden snapshot — update intentionally when the generator output changes on purpose.
enum ApacheGolden {
    static let text = #"""
# Generated by RAMP — do not edit
# Source of truth: ramp.json — regenerated on every change.

ServerRoot "/Users/t/Library/Application Support/RAMP/apache/2.4/current"
PidFile "/Users/t/Library/Application Support/RAMP/run/httpd.pid"
ServerName localhost
Listen 127.0.0.1:8080
Listen [::1]:8080

LoadModule mpm_event_module modules/mod_mpm_event.so
LoadModule authz_core_module modules/mod_authz_core.so
LoadModule authz_host_module modules/mod_authz_host.so
LoadModule unixd_module modules/mod_unixd.so
LoadModule dir_module modules/mod_dir.so
LoadModule mime_module modules/mod_mime.so
LoadModule log_config_module modules/mod_log_config.so
LoadModule alias_module modules/mod_alias.so
LoadModule rewrite_module modules/mod_rewrite.so
LoadModule headers_module modules/mod_headers.so
LoadModule setenvif_module modules/mod_setenvif.so
LoadModule env_module modules/mod_env.so
LoadModule expires_module modules/mod_expires.so
LoadModule deflate_module modules/mod_deflate.so
LoadModule filter_module modules/mod_filter.so
LoadModule proxy_module modules/mod_proxy.so
LoadModule proxy_fcgi_module modules/mod_proxy_fcgi.so

# Event MPM — modest development sizing.
StartServers 2
MinSpareThreads 25
MaxSpareThreads 75
ThreadsPerChild 25
MaxRequestWorkers 150
MaxConnectionsPerChild 0

Timeout 300
KeepAlive On
ServerTokens Prod
ServerSignature Off
ErrorLog "/Users/t/Library/Logs/RAMP/apache-error.log"
LogLevel warn
LogFormat "%h %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\"" combined
CustomLog "/Users/t/Library/Logs/RAMP/apache-access.log" combined

<IfFile "/Users/t/Library/Application Support/RAMP/apache/2.4/current/conf/mime.types">
    TypesConfig "/Users/t/Library/Application Support/RAMP/apache/2.4/current/conf/mime.types"
</IfFile>
<IfFile "!/Users/t/Library/Application Support/RAMP/apache/2.4/current/conf/mime.types">
    TypesConfig "/dev/null"
    AddType text/html .html .htm
    AddType text/css .css
    AddType text/javascript .js .mjs
    AddType application/json .json .map
    AddType application/xml .xml
    AddType text/plain .txt
    AddType image/png .png
    AddType image/jpeg .jpg .jpeg
    AddType image/gif .gif
    AddType image/webp .webp
    AddType image/avif .avif
    AddType image/svg+xml .svg
    AddType image/x-icon .ico
    AddType font/woff .woff
    AddType font/woff2 .woff2
    AddType font/ttf .ttf
    AddType font/otf .otf
    AddType application/pdf .pdf
    AddType application/zip .zip
    AddType video/mp4 .mp4
    AddType application/wasm .wasm
</IfFile>
AddDefaultCharset UTF-8

<Directory />
    AllowOverride None
    Require all denied
</Directory>
<Directory "/Users/t/Library/Application Support/RAMP/www">
    Options FollowSymLinks
    AllowOverride All
    Require all granted
</Directory>
<Directory "/Users/t/Library/Application Support/RAMP/www/default">
    Options FollowSymLinks
    AllowOverride All
    Require all granted
</Directory>
<Files ".ht*">
    Require all denied
</Files>
DirectoryIndex index.php index.html

# PHP reaches Apache only through mod_proxy_fcgi + per-branch FPM unix sockets.
<Proxy "fcgi://localhost" enablereuse=off>
</Proxy>
ProxyTimeout 300

<VirtualHost *:8080>
    ServerName localhost
    DocumentRoot "/Users/t/Library/Application Support/RAMP/www/default"
    <Directory "/Users/t/Library/Application Support/RAMP/www/default">
        <FilesMatch "\.php$">
            SetHandler "proxy:unix:/Users/t/Library/Application Support/RAMP/run/php8.5.sock|fcgi://localhost"
        </FilesMatch>
    </Directory>
</VirtualHost>

# Per-site virtual hosts (Phase 3).
IncludeOptional "/Users/t/Library/Application Support/RAMP/conf/apache/vhosts/*.conf"

"""#

    static let phpMyAdminBlock = #"""
    # phpMyAdmin — localhost only, never on project vhosts.
    Alias /phpmyadmin "/Users/t/Library/Application Support/RAMP/phpmyadmin/5.2/current"
    <Directory "/Users/t/Library/Application Support/RAMP/phpmyadmin/5.2/current">
        Options FollowSymLinks
        AllowOverride None
        Require local
        DirectoryIndex index.php
        <FilesMatch "\.php$">
            SetHandler "proxy:unix:/Users/t/Library/Application Support/RAMP/run/php8.5.sock|fcgi://localhost"
        </FilesMatch>
        <Files ".user.ini">
            Require all denied
        </Files>
    </Directory>
    <DirectoryMatch "^/Users/t/Library/Application Support/RAMP/phpmyadmin/5\.2/current/(libraries|templates|setup|sql|vendor|tmp)/">
        Require all denied
    </DirectoryMatch>

"""#

    static let elasticvueBlock = #"""
    # Elasticvue (Elasticsearch GUI) — localhost only, static files, no PHP.
    Alias /elasticvue "/Users/t/Library/Application Support/RAMP/elasticvue/1.16/current"
    <Directory "/Users/t/Library/Application Support/RAMP/elasticvue/1.16/current">
        Options FollowSymLinks
        AllowOverride None
        Require local
        DirectoryIndex index.html
        FallbackResource /elasticvue/index.html
        <FilesMatch "^(index\.html|default_clusters\.json)$">
            Header set Cache-Control "no-cache"
        </FilesMatch>
    </Directory>

"""#
}
