import Foundation
import Testing
@testable import RAMPCore

@Suite struct MySQLGeneratorTests {
    let root = GeneratorFixture.rootPath
    let logs = GeneratorFixture.logsPath

    func render(_ config: RampConfig = GeneratorFixture.config) throws -> String {
        try MySQLConfigGenerator(config: config, paths: GeneratorFixture.paths).render()
    }

    @Test func mysqldSection() throws {
        let text = try render()
        #expect(text.hasPrefix("# Generated by RAMP — do not edit\n"))
        for expected in [
            "[mysqld]",
            "basedir=\"\(root)/mysql/9.7/current\"",
            "datadir=\"\(root)/mysql-data/9.7\"",
            "socket=\"\(root)/run/mysql9.7.sock\"",
            "pid-file=\"\(root)/run/mysql9.7.pid\"",
            "port=3306",
            "bind-address=127.0.0.1",
            "mysqlx=OFF",
            "skip-log-bin",
            "log-error=\"\(logs)/mysql9.7.err\"",
            "sql_mode=\"STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION\"",
            "max_allowed_packet=1G",
            "innodb_buffer_pool_size=4G",
            "character-set-server=utf8mb4",
            "collation-server=utf8mb4_0900_ai_ci",
            "tmpdir=\"\(root)/tmp\"",
        ] {
            #expect(text.contains(expected + "\n"), "missing \(expected)")
        }
    }

    @Test func clientSections() throws {
        let text = try render()
        let sock = "socket=\"\(root)/run/mysql9.7.sock\"\nport=3306\n"
        #expect(text.contains("[client]\n" + sock))
        #expect(text.contains("[mysqladmin]\n" + sock))
        #expect(!text.contains("password"))
    }

    @Test func neverBinlogOrMysqlx() throws {
        let text = try render()
        for line in text.split(separator: "\n") {
            #expect(!line.hasPrefix("log-bin"))
            #expect(!line.hasPrefix("log_bin"))
        }
        #expect(!text.contains("mysqlx=ON"))
    }

    @Test func configValuesPropagate() throws {
        var c = GeneratorFixture.config
        c.mysql.innodbBufferPoolSize = "512M"
        c.mysql.port = 3307
        c.mysql.sqlMode = ""
        let text = try render(c)
        #expect(text.contains("innodb_buffer_pool_size=512M\n"))
        #expect(text.contains("port=3307\n"))
        #expect(text.contains("sql_mode=\"\"\n"))
    }

    @Test func invalidSizeRejected() {
        var c = GeneratorFixture.config
        c.mysql.maxAllowedPacket = "1G\nlog-bin"
        #expect(throws: GeneratorError.self) { try render(c) }
        c.mysql.maxAllowedPacket = "lots"
        #expect(throws: GeneratorError.self) { try render(c) }
    }

    @Test func notInstalledThrows() {
        var c = GeneratorFixture.config
        c.mysql.branch = "8.4"
        #expect(throws: GeneratorError.componentNotInstalled("mysql 8.4")) { try render(c) }
    }

    @Test func golden() throws {
        #expect(try render() == MySQLGolden.text)
    }
}

@Suite struct RedisGeneratorTests {
    let root = GeneratorFixture.rootPath
    let logs = GeneratorFixture.logsPath

    func render(_ config: RampConfig = GeneratorFixture.config) throws -> String {
        try RedisConfigGenerator(config: config, paths: GeneratorFixture.paths).render()
    }

    @Test func directives() throws {
        let text = try render()
        #expect(text.hasPrefix("# Generated by RAMP — do not edit\n"))
        for expected in [
            "bind 127.0.0.1 -::1", "port 6379", "protected-mode yes", "daemonize no", "supervised no",
            "dir \"\(root)/redis-data\"", "logfile \"\(logs)/redis.log\"", "pidfile \"\(root)/run/redis.pid\"",
            "save 3600 1 300 100", "appendonly no",
        ] {
            #expect(text.contains(expected + "\n"), "missing \(expected)")
        }
        #expect(!text.contains("maxmemory"))
    }

    @Test func maxmemoryOnlyWhenConfigured() throws {
        var c = GeneratorFixture.config
        c.redis.maxmemory = "512mb"
        #expect(try render(c).contains("maxmemory 512mb\n"))
        c.redis.maxmemory = "512mb\nrequirepass x"
        #expect(throws: GeneratorError.self) { try render(c) }
    }

    @Test func golden() throws {
        #expect(try render() == RedisGolden.text)
    }
}

/// Golden snapshot — update intentionally when the generator output changes on purpose.
enum MySQLGolden {
    static let text = #"""
# Generated by RAMP — do not edit
# MySQL 9.7 — started with --defaults-file.

[mysqld]
basedir="/Users/t/Library/Application Support/RAMP/mysql/9.7/current"
datadir="/Users/t/Library/Application Support/RAMP/mysql-data/9.7"
socket="/Users/t/Library/Application Support/RAMP/run/mysql9.7.sock"
pid-file="/Users/t/Library/Application Support/RAMP/run/mysql9.7.pid"
port=3306
bind-address=127.0.0.1
mysqlx=OFF
skip-log-bin
log-error="/Users/t/Library/Logs/RAMP/mysql9.7.err"
sql_mode="STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION"
max_allowed_packet=1G
innodb_buffer_pool_size=4G
character-set-server=utf8mb4
collation-server=utf8mb4_0900_ai_ci
tmpdir="/Users/t/Library/Application Support/RAMP/tmp"

[client]
socket="/Users/t/Library/Application Support/RAMP/run/mysql9.7.sock"
port=3306

[mysqladmin]
socket="/Users/t/Library/Application Support/RAMP/run/mysql9.7.sock"
port=3306

"""#
}

/// Golden snapshot — update intentionally when the generator output changes on purpose.
enum RedisGolden {
    static let text = #"""
# Generated by RAMP — do not edit

bind 127.0.0.1 -::1
port 6379
protected-mode yes
daemonize no
supervised no
pidfile "/Users/t/Library/Application Support/RAMP/run/redis.pid"
logfile "/Users/t/Library/Logs/RAMP/redis.log"
loglevel notice
dir "/Users/t/Library/Application Support/RAMP/redis-data"
dbfilename dump.rdb
save 3600 1 300 100
appendonly no

"""#
}
