import Foundation
import Testing
@testable import RAMPCore

@Suite struct PHPFPMGeneratorTests {
    let root = GeneratorFixture.rootPath
    let logs = GeneratorFixture.logsPath

    func render(_ branch: String, paths: Paths = GeneratorFixture.paths) throws -> String {
        try PHPFPMConfigGenerator(config: GeneratorFixture.config, paths: paths).render(branch: branch)
    }

    @Test func globalSection() throws {
        let text = try render("8.3")
        #expect(text.hasPrefix("; Generated by RAMP — do not edit\n"))
        #expect(text.contains("[global]\n"))
        #expect(text.contains("pid = \"\(root)/run/php8.3-fpm.pid\"\n"))
        #expect(text.contains("error_log = \"\(logs)/php8.3-fpm.log\"\n"))
        #expect(text.contains("daemonize = no\n"))
    }

    @Test func poolSection() throws {
        let text = try render("8.3")
        for expected in [
            "[www]",
            "listen = \"\(root)/run/php8.3.sock\"",
            "listen.mode = 0660",
            "pm = ondemand",
            "pm.max_children = 20",
            "pm.process_idle_timeout = 60s",
            "pm.max_requests = 500",
            "request_terminate_timeout = 300",
            "catch_workers_output = yes",
            "decorate_workers_output = no",
            "clear_env = no",
            "php_admin_value[error_log] = \"\(logs)/php8.3-error.log\"",
        ] {
            #expect(text.contains(expected + "\n"), "missing \(expected)")
        }
    }

    @Test func nonRootPool() throws {
        let text = try render("8.3")
        for line in text.split(separator: "\n") {
            #expect(!line.hasPrefix("user"))
            #expect(!line.hasPrefix("group"))
            #expect(!line.hasPrefix("listen.owner"))
            #expect(!line.hasPrefix("listen.group"))
        }
    }

    @Test func php73HasNo8xOnlyKeys() throws {
        let text = try render("7.3")
        #expect(text.contains("listen = \"\(root)/run/php7.3.sock\"\n"))
        #expect(!text.contains("pm.max_spawn_rate"))
        #expect(text.contains("decorate_workers_output = no"))
    }

    @Test func notInstalledThrows() {
        #expect(throws: GeneratorError.phpBranchNotInstalled("8.4")) { try render("8.4") }
    }

    @Test func socketTooLongThrows() {
        let longRoot = "/Users/t/" + String(repeating: "x", count: 100)
        let p = Paths(root: URL(filePath: longRoot, directoryHint: .isDirectory),
                      logs: URL(filePath: "/tmp/l", directoryHint: .isDirectory))
        #expect(throws: GeneratorError.self) { try render("8.3", paths: p) }
    }

    @Test func golden() throws {
        #expect(try render("8.3") == PHPFPMGolden.text)
    }
}

@Suite struct PHPIniGeneratorTests {
    let root = GeneratorFixture.rootPath
    let paths = GeneratorFixture.paths

    func files(_ branch: String, config: RampConfig = GeneratorFixture.config) throws -> [GeneratedFile] {
        try PHPIniGenerator(config: config, paths: paths).files(branch: branch)
    }

    func phpIni(_ branch: String, config: RampConfig = GeneratorFixture.config) throws -> String {
        try #require(try files(branch, config: config).first { $0.path == paths.phpIni(branch: branch) }).contents
    }

    func opcache(_ branch: String, config: RampConfig = GeneratorFixture.config) throws -> String {
        let url = paths.phpConfD(branch: branch).appending(path: "10-opcache.ini", directoryHint: .notDirectory)
        return try #require(try files(branch, config: config).first { $0.path == url }).contents
    }

    @Test func producesPhpIniAndOpcacheFragment() throws {
        let f = try files("8.3")
        #expect(f.map(\.path) == [
            paths.phpIni(branch: "8.3"),
            paths.phpConfD(branch: "8.3").appending(path: "10-opcache.ini", directoryHint: .notDirectory),
        ])
        #expect(f.allSatisfy { $0.mode == 0o644 })
    }

    @Test func absoluteExtensionDir() throws {
        let text = try phpIni("8.5")
        #expect(text.hasPrefix("; Generated by RAMP — do not edit\n"))
        #expect(text.contains("extension_dir=\"\(root)/php/8.5/current/\(GeneratorFixture.extRel)\"\n"))
    }

    @Test func missingExtensionDirThrows() {
        var c = GeneratorFixture.config
        c.installed["php"]!["8.3"]!.extensionDirRel = nil
        #expect(throws: GeneratorError.self) { try files("8.3", config: c) }
    }

    @Test func unifiedDefaultsAndNoOpcacheInPhpIni() throws {
        for branch in ["7.3", "8.2", "8.3", "8.5"] {
            let text = try phpIni(branch)
            for expected in [
                "memory_limit=1024M", "max_execution_time=300", "max_input_time=300",
                "post_max_size=1024M", "upload_max_filesize=1024M",
                "display_errors=On", "display_startup_errors=On", "log_errors=On",
                "error_reporting=E_ALL", "date.timezone=Europe/Bratislava",
                "mysqli.default_socket=\"\(root)/run/mysql9.7.sock\"",
                "pdo_mysql.default_socket=\"\(root)/run/mysql9.7.sock\"",
                "upload_tmp_dir=\"\(root)/tmp\"", "sys_temp_dir=\"\(root)/tmp\"", "session.save_path=\"\(root)/tmp\"",
            ] {
                #expect(text.contains(expected + "\n"), "\(branch) missing \(expected)")
            }
            #expect(!text.contains("opcache"))
            #expect(!text.contains("xdebug"))
        }
    }

    @Test func overridesRenderedAndEncoded() throws {
        var c = GeneratorFixture.config
        c.php.globalIniOverrides = ["memory_limit": "2048M", "disable_functions": "", "user_agent": "a;b ${X}"]
        c.php.branches["8.3"] = PHPBranchSettings(iniOverrides: ["error_reporting": "E_ALL & ~E_DEPRECATED"])
        let text = try phpIni("8.3", config: c)
        #expect(text.contains("memory_limit=2048M\n"))
        #expect(!text.contains("memory_limit=1024M"))
        #expect(text.contains("error_reporting=E_ALL & ~E_DEPRECATED\n"))
        #expect(text.contains("disable_functions=\n"))
        #expect(text.contains(#"user_agent="a;b \${X}""# + "\n"))
        #expect(try phpIni("8.2", config: c).contains("error_reporting=E_ALL\n"))
    }

    @Test func protectedOverrideThrows() {
        var c = GeneratorFixture.config
        c.php.globalIniOverrides = ["opcache.enable": "0"]
        #expect(throws: GeneratorError.invalidValue(key: "php.iniOverrides", value: "opcache.enable")) {
            try files("8.3", config: c)
        }
    }

    @Test func opcacheFragment() throws {
        for branch in ["7.3", "8.2", "8.3"] {
            let text = try opcache(branch)
            for expected in [
                "zend_extension=opcache", "opcache.enable=1", "opcache.enable_cli=0",
                "opcache.memory_consumption=256", "opcache.interned_strings_buffer=32",
                "opcache.max_accelerated_files=50000", "opcache.validate_timestamps=1", "opcache.revalidate_freq=0",
            ] {
                #expect(text.contains(expected + "\n"), "\(branch) missing \(expected)")
            }
        }
    }

    @Test func jitOffOnlyWhereItExists() throws {
        #expect(try opcache("8.3").contains("opcache.jit=disable\nopcache.jit_buffer_size=0\n"))
        #expect(!(try opcache("7.3").contains("jit")))
    }

    /// ISS-001: `zend_extension=opcache` only for a shared opcache build (8.5+ is always static).
    @Test func opcacheBuildType() throws {
        // No recorded build type → inferred: < 8.5 shared, ≥ 8.5 static.
        #expect(try opcache("8.3").contains("zend_extension=opcache\n"))
        #expect(!(try opcache("8.5").contains("zend_extension")))
        #expect(try opcache("8.5").contains("opcache.enable=1\n"))
        // Recorded build type wins.
        var c = GeneratorFixture.config
        c.installed["php"]!["8.3"]!.opcache = "static"
        c.installed["php"]!["8.5"]!.opcache = "shared"
        #expect(!(try opcache("8.3", config: c).contains("zend_extension")))
        #expect(try opcache("8.5", config: c).contains("zend_extension=opcache\n"))
        c.installed["php"]!["8.3"]!.opcache = "bogus"
        #expect(throws: GeneratorError.self) { try files("8.3", config: c) }
    }

    @Test func notInstalledThrows() {
        #expect(throws: GeneratorError.phpBranchNotInstalled("8.4")) { try files("8.4") }
    }

    @Test func deterministic() throws {
        var c = GeneratorFixture.config
        c.php.globalIniOverrides = ["b.key": "1", "a.key": "2", "c.key": "3"]
        #expect(try files("8.3", config: c) == (try files("8.3", config: c)))
    }

    @Test func golden() throws {
        #expect(try phpIni("8.3") == PHPIniGolden.text)
        #expect(try opcache("8.3") == PHPIniGolden.opcache)
    }
}

/// Golden snapshot — update intentionally when the generator output changes on purpose.
enum PHPFPMGolden {
    static let text = #"""
; Generated by RAMP — do not edit
; PHP 8.3 FPM — supervised by RAMP (daemonize = no), runs as the logged-in user.

[global]
pid = "/Users/t/Library/Application Support/RAMP/run/php8.3-fpm.pid"
error_log = "/Users/t/Library/Logs/RAMP/php8.3-fpm.log"
log_level = notice
daemonize = no

[www]
listen = "/Users/t/Library/Application Support/RAMP/run/php8.3.sock"
listen.mode = 0660
pm = ondemand
pm.max_children = 20
pm.process_idle_timeout = 60s
pm.max_requests = 500
request_terminate_timeout = 300
catch_workers_output = yes
decorate_workers_output = no
; Keep the environment so OBJC_DISABLE_INITIALIZE_FORK_SAFETY reaches the workers.
clear_env = no
php_admin_value[error_log] = "/Users/t/Library/Logs/RAMP/php8.3-error.log"
php_admin_flag[log_errors] = on

"""#
}

/// Golden snapshot — update intentionally when the generator output changes on purpose.
enum PHPIniGolden {
    static let text = #"""
; Generated by RAMP — do not edit
; PHP 8.3 — RAMP defaults, then global and per-branch overrides. conf.d/*.ini is loaded after this file.

[PHP]
extension_dir="/Users/t/Library/Application Support/RAMP/php/8.3/current/lib/php/extensions/no-debug-non-zts-20230831"
curl.cainfo="/Users/t/Library/Application Support/RAMP/php/8.3/current/ssl/cert.pem"
openssl.cafile="/Users/t/Library/Application Support/RAMP/php/8.3/current/ssl/cert.pem"
memory_limit=1024M
max_execution_time=300
max_input_time=300
post_max_size=1024M
upload_max_filesize=1024M
display_errors=On
display_startup_errors=On
log_errors=On
error_reporting=E_ALL
date.timezone=Europe/Bratislava
mysqli.default_socket="/Users/t/Library/Application Support/RAMP/run/mysql9.7.sock"
pdo_mysql.default_socket="/Users/t/Library/Application Support/RAMP/run/mysql9.7.sock"
upload_tmp_dir="/Users/t/Library/Application Support/RAMP/tmp"
sys_temp_dir="/Users/t/Library/Application Support/RAMP/tmp"
session.save_path="/Users/t/Library/Application Support/RAMP/tmp"

"""#

    static let opcache = #"""
; Generated by RAMP — do not edit
; OPcache — PHP 8.3 (shared build)
zend_extension=opcache
opcache.enable=1
opcache.enable_cli=0
opcache.memory_consumption=256
opcache.interned_strings_buffer=32
opcache.max_accelerated_files=50000
opcache.validate_timestamps=1
opcache.revalidate_freq=0
opcache.jit=disable
opcache.jit_buffer_size=0

"""#
}
