import Foundation
import Testing
@testable import RAMPCore

/// Vhost fixture on top of `GeneratorFixture` (php 7.3/8.2/8.3/8.5, port 8080).
enum VhostGeneratorFixture {
    static let ids = (0..<4).map { UUID(uuidString: "00000000-0000-0000-0000-00000000010\($0)")! }

    static var vhosts: [Vhost] {
        [
            Vhost(id: ids[0], domain: "asteel.local", aliases: ["admin.asteel.local"],
                  docroot: "/Users/t/Sites/asteel/www", phpBranch: "8.3"),
            Vhost(id: ids[1], domain: "tyrestock.local", aliases: ["zz.tyrestock.local", "api.tyrestock.local"],
                  docroot: "/Users/t/Sites/tyrestock/www", phpBranch: "7.3"),
            Vhost(id: ids[2], domain: "mysite.local", docroot: "/Users/t/Sites/my site"),
            Vhost(id: ids[3], domain: "off.local", docroot: "/Users/t/Sites/off", phpBranch: "8.2", enabled: false),
        ]
    }

    static var config: RampConfig {
        var c = GeneratorFixture.config
        c.vhosts = vhosts
        return c
    }
}

@Suite struct VhostGeneratorTests {
    let paths = GeneratorFixture.paths
    let root = GeneratorFixture.rootPath
    let logs = GeneratorFixture.logsPath

    func files(_ config: RampConfig = VhostGeneratorFixture.config) throws -> [GeneratedFile] {
        try VhostConfigGenerator(config: config, paths: paths).files()
    }

    func vhostFile(_ domain: String) -> URL {
        paths.apacheVhostsDir.appending(path: "\(domain).conf", directoryHint: .notDirectory)
    }

    @Test func oneFilePerEnabledVhostSortedByDomain() throws {
        let out = try files()
        #expect(out.map(\.path) == ["asteel.local", "mysite.local", "tyrestock.local"].map(vhostFile))
        #expect(out.allSatisfy { $0.mode == 0o644 })
    }

    @Test func goldenAsteel() throws {
        let asteel = try #require(try files().first)
        #expect(asteel.contents == """
        # Generated by RAMP — do not edit
        <VirtualHost *:8080>
            ServerName asteel.local
            ServerAlias admin.asteel.local
            DocumentRoot "/Users/t/Sites/asteel/www"
            <Directory "/Users/t/Sites/asteel/www">
                Options FollowSymLinks
                AllowOverride All
                Require all granted
                CGIPassAuth On
                <FilesMatch "\\.php$">
                    SetHandler "proxy:unix:\(root)/run/php8.3.sock|fcgi://localhost"
                </FilesMatch>
            </Directory>
            ErrorLog "\(logs)/apache-asteel.local-error.log"
        </VirtualHost>

        """)
    }

    @Test func aliasesSortedOnOneLineAndOmittedWhenEmpty() throws {
        let out = try files()
        let tyrestock = try #require(out.first { $0.path == vhostFile("tyrestock.local") })
        #expect(tyrestock.contents.contains("    ServerAlias api.tyrestock.local zz.tyrestock.local\n"))
        #expect(tyrestock.contents.contains("run/php7.3.sock|"))
        let mysite = try #require(out.first { $0.path == vhostFile("mysite.local") })
        #expect(!mysite.contents.contains("ServerAlias"))
    }

    @Test func docrootWithSpaceQuotedAndDefaultBranch() throws {
        let mysite = try #require(try files().first { $0.path == vhostFile("mysite.local") })
        #expect(mysite.contents.contains("    DocumentRoot \"/Users/t/Sites/my site\"\n"))
        #expect(mysite.contents.contains("    <Directory \"/Users/t/Sites/my site\">\n"))
        // phpBranch nil → highest installed+enabled branch (8.5).
        #expect(mysite.contents.contains("SetHandler \"proxy:unix:\(root)/run/php8.5.sock|fcgi://localhost\""))
    }

    @Test func defaultBranchFollowsApacheDefaultPHP() throws {
        var c = VhostGeneratorFixture.config
        c.apache.defaultPHP = "8.2"
        let mysite = try #require(try files(c).first { $0.path == vhostFile("mysite.local") })
        #expect(mysite.contents.contains("run/php8.2.sock|"))
    }

    @Test func noPHPInstalledMeansNoHandler() throws {
        var c = VhostGeneratorFixture.config
        c.installed["php"] = nil
        c.vhosts = [Vhost(domain: "plain.local", docroot: "/Users/t/Sites/plain")]
        let out = try files(c)
        #expect(out.count == 1)
        #expect(!out[0].contents.contains("FilesMatch"))
        #expect(!out[0].contents.contains("SetHandler"))
        #expect(out[0].contents.contains("    CGIPassAuth On\n"))
    }

    @Test func missingOrDisabledBranchRejected() {
        var c = VhostGeneratorFixture.config
        c.vhosts[0].phpBranch = "5.6"
        #expect(throws: GeneratorError.phpBranchNotInstalled("5.6")) { try files(c) }
        var d = VhostGeneratorFixture.config
        d.php.branches["8.3"] = PHPBranchSettings(enabled: false)
        #expect(throws: GeneratorError.phpBranchNotInstalled("8.3")) { try files(d) }
    }

    @Test func disabledVhostWithBadBranchIgnored() throws {
        var c = VhostGeneratorFixture.config
        c.vhosts[3].phpBranch = "5.6"
        #expect(try files(c).count == 3)
    }

    @Test(arguments: [
        "asteel.local\nInclude /etc/passwd", "bad domain.local", "evil\".local", "../x.local", "a/b.local",
        "localhost", "nodot", "",
    ])
    func invalidDomainRejected(_ domain: String) {
        var c = VhostGeneratorFixture.config
        c.vhosts = [Vhost(domain: domain, docroot: "/Users/t/Sites/x")]
        #expect(throws: GeneratorError.self) { try files(c) }
    }

    @Test func invalidAliasRejected() {
        var c = VhostGeneratorFixture.config
        c.vhosts[0].aliases = ["ok.asteel.local", "x.local\n</VirtualHost>"]
        #expect(throws: GeneratorError.self) { try files(c) }
    }

    @Test(arguments: ["/Users/t/Sites/x\n</Directory>", "/Users/t/\u{1}x", "/Users/t/x\ty", "relative/path", ""])
    func unsafeDocrootRejected(_ docroot: String) {
        var c = VhostGeneratorFixture.config
        c.vhosts = [Vhost(domain: "x.local", docroot: docroot)]
        #expect(throws: GeneratorError.self) { try files(c) }
    }

    @Test func quoteInDocrootEscaped() throws {
        var c = VhostGeneratorFixture.config
        c.vhosts = [Vhost(domain: "q.local", docroot: "/Users/t/Sites/a\"b", phpBranch: "8.3")]
        let out = try files(c)
        #expect(out[0].contents.contains("DocumentRoot \"/Users/t/Sites/a\\\"b\"\n"))
    }

    @Test func domainNormalizedForFilename() throws {
        var c = VhostGeneratorFixture.config
        c.vhosts = [Vhost(domain: "Upper.Local", docroot: "/Users/t/Sites/u", phpBranch: "8.3")]
        let out = try files(c)
        #expect(out.map(\.path) == [vhostFile("upper.local")])
        #expect(out[0].contents.contains("ServerName upper.local\n"))
    }

    @Test func neverSSLOrLegacyPHP() throws {
        for f in try files() {
            let lower = f.contents.lowercased()
            for forbidden in ["443", "ssl", "fastcgi_", "fcgid", "php_module", "libphp", "addhandler"] {
                #expect(!lower.contains(forbidden), "\(f.path.lastPathComponent) must not contain \(forbidden)")
            }
        }
    }

    @Test func deterministic() throws {
        #expect(try files() == files())
    }
}

@Suite struct ConfigWriterPruneTests {
    func tempPaths() -> Paths {
        let base = URL(filePath: "/tmp/ramp p-\(UUID().uuidString.prefix(8))", directoryHint: .isDirectory)
        return Paths(root: base.appending(path: "root", directoryHint: .isDirectory),
                     logs: base.appending(path: "logs", directoryHint: .isDirectory))
    }

    func mtime(_ url: URL) throws -> Date {
        try #require(try FileManager.default.attributesOfItem(atPath: url.path(percentEncoded: false))[.modificationDate] as? Date)
    }

    @Test func disableOneVhostPrunesOnlyItsFile() throws {
        let p = tempPaths()
        defer { try? FileManager.default.removeItem(at: p.root.deletingLastPathComponent()) }
        let writer = ConfigWriter(paths: p)
        var config = VhostGeneratorFixture.config
        let first = try VhostConfigGenerator(config: config, paths: p).files()
        #expect(first.count == 3)
        #expect(try writer.write(first).count == 3)
        let asteel = first[0].path, mysite = first[1].path, tyrestock = first[2].path
        // Make "unchanged" detectable: backdate mtimes.
        let old = Date(timeIntervalSince1970: 1_000_000_000)
        for u in [asteel, tyrestock] {
            try FileManager.default.setAttributes([.modificationDate: old], ofItemAtPath: u.path(percentEncoded: false))
        }

        config.vhosts[2].enabled = false // mysite.local
        let second = try VhostConfigGenerator(config: config, paths: p).files()
        #expect(try writer.write(second).isEmpty)
        let removed = try writer.prune(directory: p.apacheVhostsDir, keeping: Set(second.map(\.path)), extension: "conf")
        #expect(removed.map(\.lastPathComponent) == ["mysite.local.conf"])
        #expect(!FileManager.default.fileExists(atPath: mysite.path(percentEncoded: false)))
        #expect(try mtime(asteel) == old)
        #expect(try mtime(tyrestock) == old)
    }

    @Test func leavesOtherExtensionsSubdirsAndSymlinks() throws {
        let p = tempPaths()
        defer { try? FileManager.default.removeItem(at: p.root.deletingLastPathComponent()) }
        let fm = FileManager.default
        let dir = p.apacheVhostsDir
        try fm.createDirectory(at: dir, withIntermediateDirectories: true)
        let keep = dir.appending(path: "keep.conf")
        let stale = dir.appending(path: "stale.conf")
        let other = dir.appending(path: "notes.txt")
        let sub = dir.appending(path: "sub.conf", directoryHint: .isDirectory)
        let inner = sub.appending(path: "inner.conf")
        let outside = p.root.appending(path: "outside.conf")
        let link = dir.appending(path: "link.conf")
        for f in [keep, stale, other, outside] { #expect(fm.createFile(atPath: f.path(percentEncoded: false), contents: Data("x".utf8))) }
        try fm.createDirectory(at: sub, withIntermediateDirectories: true)
        #expect(fm.createFile(atPath: inner.path(percentEncoded: false), contents: Data("x".utf8)))
        try fm.createSymbolicLink(atPath: link.path(percentEncoded: false), withDestinationPath: outside.path(percentEncoded: false))

        let removed = try ConfigWriter(paths: p).prune(directory: dir, keeping: [keep], extension: "conf")
        #expect(removed.map(\.lastPathComponent) == ["stale.conf"])
        for u in [keep, other, inner, outside] { #expect(fm.fileExists(atPath: u.path(percentEncoded: false))) }
        #expect((try? fm.destinationOfSymbolicLink(atPath: link.path(percentEncoded: false))) != nil)
    }

    @Test func missingDirectoryIsEmpty() throws {
        let p = tempPaths()
        #expect(try ConfigWriter(paths: p).prune(directory: p.apacheVhostsDir, keeping: [], extension: "conf").isEmpty)
    }

    @Test func refusesDirectoriesOutsideRoot() throws {
        let p = tempPaths()
        let writer = ConfigWriter(paths: p)
        #expect(throws: ConfigWriterError.self) {
            try writer.prune(directory: p.root.deletingLastPathComponent(), keeping: [], extension: "conf")
        }
        #expect(throws: ConfigWriterError.self) {
            try writer.prune(directory: p.root.appending(path: "../x", directoryHint: .isDirectory), keeping: [], extension: "conf")
        }
        #expect(throws: ConfigWriterError.self) {
            try writer.prune(directory: p.root, keeping: [], extension: "conf")
        }
    }
}
