import Foundation

public enum MAMPImportError: Error, Equatable, LocalizedError {
    /// Unterminated / mismatched block; `line` is 1-based.
    case malformed(line: Int)
    /// Input larger than `MAMPConfigParser.maxBytes`.
    case tooLarge
    /// The config file could not be read.
    case unreadable(path: String)

    public var errorDescription: String? {
        switch self {
        case .malformed(let line): "MAMP httpd.conf is malformed near line \(line)"
        case .tooLarge: "MAMP httpd.conf is larger than 5 MB"
        case .unreadable(let path): "Cannot read \(path)"
        }
    }
}

/// One `<VirtualHost>` block of MAMP PRO's generated httpd.conf / httpd-ssl.conf.
public struct MAMPVhost: Sendable, Equatable, Hashable {
    /// Lowercased `ServerName` without a `:port` suffix; `""` if the block has none.
    public var serverName: String
    /// Lowercased `ServerAlias` names in file order, deduplicated (never the server name itself).
    public var aliases: [String]
    public var documentRoot: String?
    /// Full MAMP PHP version (`8.3.14`) from `Action php-fastcgi "/fcgi-bin/php8.3.14.fcgi"`,
    /// or `M.m` from a `SetHandler "proxy:…php8.3…"` (future MAMP).
    public var phpVersion: String?
    /// `Redirect [status] /path <URL>` target URL (only when a URL is given).
    public var redirectTarget: String?
    /// 1-based line of the `<VirtualHost …>` tag.
    public var line: Int

    public init(serverName: String, aliases: [String], documentRoot: String?, phpVersion: String?,
                redirectTarget: String?, line: Int) {
        self.serverName = serverName
        self.aliases = aliases
        self.documentRoot = documentRoot
        self.phpVersion = phpVersion
        self.redirectTarget = redirectTarget
        self.line = line
    }
}

/// Line-oriented parser for Apache configs as generated by MAMP PRO (plan 07-03). Pure, no I/O.
///
/// Tracks a block stack (`<Tag …>` / `</Tag>`), splits arguments Apache-style (quotes, backslash
/// escapes, `\` line continuation), ignores `#` comments. `Include` is reported, never followed.
public enum MAMPConfigParser {
    public static let maxBytes = 5 * 1024 * 1024

    public struct Result: Sendable, Equatable {
        public var vhosts: [MAMPVhost]
        /// Arguments of top-level `Include` / `IncludeOptional` directives (not followed).
        public var includes: [String]
    }

    public static func parse(_ text: String, port: Int) throws -> [MAMPVhost] {
        try parseDetailed(text, port: port).vhosts
    }

    public static func parseDetailed(_ text: String, port: Int) throws -> Result {
        guard text.utf8.count <= maxBytes else { throw MAMPImportError.tooLarge }

        struct Open { let name: String; let line: Int }
        var stack: [Open] = []
        var current: MAMPVhost?
        var vhostDepth = 0
        var result = Result(vhosts: [], includes: [])

        for (lineNo, raw) in logicalLines(text) {
            let line = raw.trimmingCharacters(in: .whitespaces)
            if line.isEmpty || line.hasPrefix("#") { continue }

            if line.hasPrefix("</") {
                let name = line.dropFirst(2).prefix { $0 != ">" && !$0.isWhitespace }.lowercased()
                guard let open = stack.popLast(), open.name == name else {
                    throw MAMPImportError.malformed(line: lineNo)
                }
                if current != nil, stack.count < vhostDepth, let done = current {
                    result.vhosts.append(done)
                    current = nil
                }
                continue
            }
            if line.hasPrefix("<") {
                var inner = line.dropFirst()
                if inner.hasSuffix(">") { inner = inner.dropLast() }
                let args = splitArguments(String(inner))
                guard let tag = args.first?.lowercased(), !tag.isEmpty else {
                    throw MAMPImportError.malformed(line: lineNo)
                }
                if tag == "virtualhost" {
                    // A vhost nested in a vhost is not valid Apache syntax.
                    if stack.contains(where: { $0.name == "virtualhost" }) { throw MAMPImportError.malformed(line: lineNo) }
                    let matches = args.dropFirst().contains { addr in
                        addr.split(separator: ":").last.map { Int($0) == port } ?? false
                    }
                    stack.append(Open(name: tag, line: lineNo))
                    if matches {
                        current = MAMPVhost(serverName: "", aliases: [], documentRoot: nil, phpVersion: nil,
                                            redirectTarget: nil, line: lineNo)
                        vhostDepth = stack.count
                    }
                } else {
                    stack.append(Open(name: tag, line: lineNo))
                }
                continue
            }

            let args = splitArguments(line)
            guard let directive = args.first?.lowercased() else { continue }
            let values = Array(args.dropFirst())

            guard var vhost = current else {
                if stack.isEmpty, directive == "include" || directive == "includeoptional", let path = values.first {
                    result.includes.append(path)
                }
                continue
            }
            apply(directive: directive, values: values, to: &vhost)
            current = vhost
        }

        if let open = stack.first { throw MAMPImportError.malformed(line: open.line) }
        return result
    }

    // MARK: Directives

    private static func apply(directive: String, values: [String], to vhost: inout MAMPVhost) {
        switch directive {
        case "servername":
            guard let value = values.first else { return }
            vhost.serverName = hostName(value)
            vhost.aliases.removeAll { $0 == vhost.serverName }
        case "serveralias":
            for name in values.map(hostName) where !name.isEmpty
                && name != vhost.serverName && !vhost.aliases.contains(name) {
                vhost.aliases.append(name)
            }
        case "documentroot":
            if let value = values.first { vhost.documentRoot = value }
        case "action":
            if let version = values.lazy.compactMap(fcgiVersion).first { vhost.phpVersion = version }
        case "sethandler":
            if let value = values.first, value.lowercased().hasPrefix("proxy:"), let version = proxyVersion(value) {
                vhost.phpVersion = version
            }
        case "redirect":
            if let target = values.last, target.contains("://") { vhost.redirectTarget = target }
        default:
            break
        }
    }

    /// `Host.Local:80` → `host.local`.
    private static func hostName(_ raw: String) -> String {
        var name = raw.trimmingCharacters(in: .whitespaces).lowercased()
        if let colon = name.lastIndex(of: ":"), name[name.index(after: colon)...].allSatisfy(\.isNumber),
           colon != name.startIndex {
            name = String(name[..<colon])
        }
        return name
    }

    /// `/fcgi-bin/php8.3.14.fcgi` → `8.3.14`.
    static func fcgiVersion(_ value: String) -> String? {
        guard let match = value.firstMatch(of: /php(\d+\.\d+(?:\.\d+)?)\.fcgi/) else { return nil }
        return String(match.1)
    }

    /// `proxy:unix:/…/php8.3-fpm.sock|fcgi://localhost` → `8.3`.
    static func proxyVersion(_ value: String) -> String? {
        guard let match = value.firstMatch(of: /php-?(\d+)\.(\d+)/) else { return nil }
        return "\(match.1).\(match.2)"
    }

    // MARK: Tokenizing

    /// Physical lines (LF, CRLF or CR) joined on trailing `\` (continuation). Yields the 1-based start line.
    static func logicalLines(_ text: String) -> [(Int, String)] {
        var out: [(Int, String)] = []
        var buffer = ""
        var start = 0
        for (index, rawLine) in text.split(omittingEmptySubsequences: false,
                                                     whereSeparator: { $0 == "\n" || $0 == "\r\n" || $0 == "\r" })
            .enumerated() {
            // "\r\n" is a single Character in Swift, so CRLF is split here, not stripped later.
            let line = rawLine
            if buffer.isEmpty { start = index + 1 }
            let trimmedEnd = line.reversed().drop { $0 == " " || $0 == "\t" }
            if trimmedEnd.first == "\\", !line.trimmingCharacters(in: .whitespaces).hasPrefix("#") {
                buffer += String(line[..<line.lastIndex(of: "\\")!]) + " "
                continue
            }
            out.append((start, buffer + line))
            buffer = ""
        }
        if !buffer.isEmpty { out.append((start, buffer)) }
        return out
    }

    /// Apache-style argument splitting: whitespace separated, `"…"` / `'…'` quoting, `\x` escapes inside quotes.
    static func splitArguments(_ line: String) -> [String] {
        var args: [String] = []
        var current = ""
        var quote: Character?
        var inToken = false
        var iterator = line.makeIterator()
        while let ch = iterator.next() {
            if let q = quote {
                if ch == "\\", let next = iterator.next() {
                    if next == q || next == "\\" { current.append(next) } else { current.append(ch); current.append(next) }
                } else if ch == q {
                    quote = nil
                } else {
                    current.append(ch)
                }
            } else if ch == " " || ch == "\t" {
                if inToken { args.append(current); current = ""; inToken = false }
            } else if (ch == "\"" || ch == "'") && !inToken {
                quote = ch
                inToken = true
            } else {
                current.append(ch)
                inToken = true
            }
        }
        if inToken { args.append(current) }
        return args
    }
}
